spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_lab
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        use_sql_comments: false
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
